spring:
  application:
    name: "profile"
  #########################
  #       DATABASE
  #########################
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:1234}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071}"
  #### FALLBACK
  cloud:
    loadbalancer:
      retry:
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  profiles:
    active: "dev"
accounts:
  message: "profile server message 1234"

#########################
#       SERVER
#########################
server:
  port: 8081
  url: "http://localhost:${server.port}"
  version: "1.0"
profile:
  message: "Hello from profile service!"

#########################
#       EUREKA
#########################
eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8070/eureka/}"
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

#########################
#       ACTUATOR
#########################
management:
  endpoints:
    web:
      exposure:
        include: "*"
        # include: health, info, ... (bu usulda aloxida-aloxida chiqarishimiz mumkin)
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: "profile"
    description: "profile microservice card application"
    version: "1.0.0"