spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
#        git:
#          uri: "https://github.com/sardoruktamov/config-server-properties.git"
#          username: "sardoruktamov"
#          password: yourPassword
#          default-label: "main"
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
server:
  port: 8071
#########################
#       ACTUATOR
#########################
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
        # include: health, info, ... (bu usulda aloxida-aloxida chiqarishimiz mumkin)
#########################
#       EUREKA
#########################
eureka:
  client:
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8070/eureka/}"
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

#########################
#       encrypt key
#########################
encrypt:
  key: "MySecretKey1234!"